server:
  port: 8080
  servlet:
    context-path: /api

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: huutanelastic1412
  mail:
    host: smtp.gmail.com
    port: 587
    username: huutankg2005@gmail.com
    password: ${MAIL_APP_PS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/t5
    username: postgres
    password: huutawn1412
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}
jwt:
  signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
  valid-duration: 7200 #in hours
  refreshable-duration: 72000 #in hours
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  secret-key: ${API_SECRET}
